name: Build project and run Lighthouse CI
on:
    pull_request:
        branches: ['main']

jobs:
    lighthouse:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@main

            - name: LH step1 -> Use Node.js ${{ matrix.node-version }}
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: LH step 2 -> Build
              run: npm run build

            - name: LH step 3 -> Run Lighthouse CI
            - run: |
                    npm i -g @lhci/cli@0.6.x
                    lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed"
