name: Build project and run Lighthouse CI
on:
    pull_request:
        branches: ['main']

jobs:
    lighthouse:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@main
            - name: step1 -> Use Node.js ${{ matrix.node-version }}
              uses: foo-software/lighthouse-check-action@master
              with:
                  urls: 'https://www.foo.software,https://www.google.com'
