name: General Workflow

on:
    pull_request:
        branches: ['main']
        paths-ignore:
          - '**.md'
          - 'docs/**'
    # schedule:
      # - cron: '0 5 * * 1' # run pipeline every Monday at 5:00 AM UTC

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@main

            - name: step1 -> Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ matrix.node-version }}

            - name: step 2 -> Build
              run: npm i
              # run: ci

            - name: step 3 -> Run lint
              run: npm run lint
            # - name: step 4 -> Run test
            #   run: npm run test
            # env:
            #     MY_SECRET: ${{ secrets.MY_SECRET }}
            # Run lighthouse CI
            - uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: LH step 2 -> Build
              run: npm run build

            - name: LH step 3 -> Run Lighthouse CI
              run: |
                    npm i -g @lhci/cli@0.6.x
                    lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed"

