name: Lint and Test

on:
    pull_request:
        branches: ['main']

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4

            - name: step1 -> Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: step 2 -> Build
              run: npm i
              # run: ci
            - name: step 3 -> Run lint
              run: npm run lint
            # - name: step 4 -> Run test
            #   run: npm run test
